gui:
  showIcons: true
  showBottomLine: false
  theme:
    selectedLineBgColor:
      - default
    selectedRangeBgColor:
      - default
git:
  paging:
    pager: delta --dark --paging=never
  log:
    showGraph: always
    showWholeGraph: true
  branchLogCmd: "git log --graph --color --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%n%C(reset)%C(dim cyan)Author: %an <%ae>%n%C(reset)%C(white)%w(0,4,4)%B%n%C(reset)' {{branchName}} --"
os:
  editCommand: "code"
  editCommandTemplate: '{{editor}} --goto -- {{filename}}:{{line}}'
  openCommand: "code -rg {{filename}}"
promptToReturnFromSubprocess: false
