os:
  editCommand: "nvim"
  openCommand: "nvim --server $NVIM_LISTEN_ADDRESS --remote-send 'q' && nvim --server $NVIM_LISTEN_ADDRESS --remote-tab-silent {{filename}}"
promptToReturnFromSubprocess: false
