git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
os:
  editCommand: "nvim"
  openCommand: "nvim --server $NVIM_LISTEN_ADDRESS --remote-send 'q' && nvim --server $NVIM_LISTEN_ADDRESS --remote-silent {{filename}}"
promptToReturnFromSubprocess: false
