gui:
  nerdFontsVersion: '3'
  showBottomLine: false
  showListFooter: false
  showRootItemInFileTree: false
  useHunkModeInStagingView: true
  theme:
    selectedLineBgColor:
      - '#393939'
  border: 'hidden'
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 2
git:
  diffRenderers:
    - command: delta --paging=never
  log:
    showGraph: always
    # showWholeGraph: true
    # branchLogCmd: "git log --graph --color --abbrev-commit --decorate --relative-date --pretty=medium {{branchName}} --"
    # branchLogCmd: "git log --graph --color --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%n%C(reset)%C(dim cyan)%an <%ae>%n%C(reset)%C(white)%w(0,4,4)%B%C(reset)' {{branchName}} --"
    # allBranchesLogCmd: "git log --graph --all --color=always --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim cyan)- %an%C(reset)%C(bold yellow)%d%C(reset)'"
  # same format both sides: branch-scoped on <3>, whole repo on <a> from status
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%n%C(reset)%C(dim cyan)%an <%ae>%n%C(reset)%C(white)%w(0,4,4)%B%C(reset)' {{branchName}} --"
  allBranchesLogCmds:
    - "git log --graph --all --color=always --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%n%C(reset)%C(dim cyan)%an <%ae>%n%C(reset)%C(white)%w(0,4,4)%B%C(reset)'"
os:
  open: "^open -R {{filename}}"
  editPreset: 'nvim-remote'
  edit: >-
    if not ($env | columns | any { |col| $col == 'NVIM' }) {

        nvim -- {{filename}}
    } else {

        nvim --server $env.NVIM --remote-send "q"
        nvim --server $env.NVIM --remote {{filename}}
    }
  editAtLine: >-
    if not ($env | columns | any { |col| $col == 'NVIM' }) {

        nvim +{{line}} -- {{filename}}
    } else {

        nvim --server $env.NVIM --remote-send "q"
        nvim --server $env.NVIM --remote {{filename}}
        nvim --server $env.NVIM --remote-send ":{{line}}<CR>"
    }
  openDirInEditor: >-
    if not ($env | columns | any { |col| $col == 'NVIM' }) {

        nvim -- {{dir}}
    } else {

        nvim --server $env.NVIM --remote-send "q"
        nvim --server $env.NVIM --remote {{dir}}
    }
notARepository: 'quit'
promptToReturnFromSubprocess: false
keybinding:
  universal:
    confirm-alt1: <disabled>
    copyToClipboard: 'y'
