#!/usr/bin/env sh

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=display_added action="sleep 2 && $HOME/.config/yabai/display_changed.sh"
yabai -m signal --add event=display_removed action="$HOME/.config/yabai/display_changed.sh"

$HOME/.config/yabai/display_changed.sh

yabai -m config external_bar               all:34:0     \
                mouse_follows_focus        off          \
                focus_follows_mouse        off          \
                                                        \
                window_zoom_persist        off          \
                window_placement           second_child \
                window_shadow              float        \
                                                        \
                window_opacity             off          \
                active_window_opacity      1.0          \
                normal_window_opacity      1.0          \
                                                        \
                window_border              off          \
                window_border_hidpi        off          \
                window_border_blur         off          \
                window_border_width        3            \
                active_window_border_color 0x99798286   \
                normal_window_border_color 0x6624273a   \
                                                        \
                insert_feedback_color      0xff9dd274   \
                split_ratio                0.50         \
                auto_balance               on           \
                                                        \
                mouse_modifier             alt          \
                mouse_action1              move         \
                mouse_action2              resize       \
                mouse_drop_action          swap         \
                                                        \
                top_padding                8            \
                bottom_padding             8            \
                left_padding               8            \
                right_padding              8            \
                window_gap                 8

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(Calculator|Software Update|Dictionary|System Settings|System Information|zoom.us|Photo Booth|Archive Utility|Python|App Store|Steam|Activity Monitor|Spotify|Numi|Finder|KiCad|LINE)$" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="Arc browser" app="^Arc$" title="^(Peeranut|General|Max|Shortcuts|Links|Advanced)$" manage=off
yabai -m rule --add label="Arc PiP" app="^Arc$" subrole="^AXSystemDialog$" manage=off
yabai -m rule --add label="Arc Little" app="^Arc$" title="^Space.*$" manage=off

# default layout (can be bsp, stack or float)
yabai -m config layout bsp

echo "yabai configuration loaded..."
