-- load plugin configs

require('plugins-config.autopairs-config')
require('plugins-config.gitsigns-config')
require('plugins-config.telescope-config')
require('plugins-config.toggleterm-config')
require('plugins-config.todo-comments-config')
require('plugins-config.colorizer-config')
require('plugins-config.indent-blankline-config')
require('plugins-config.focus-config')
require('plugins-config.marks-config')
require('plugins-config.comment-config')
require('plugins-config.hlslens-config')
require('plugins-config.lualine-config')
require('plugins-config.session-manager-config')
require('plugins-config.navic-config')
require('plugins-config.incline-config')
require('plugins-config.illuminate-config')
require('plugins-config.git-conflict-config')
require('plugins-config.ufo-config')
require('plugins-config.noice-config')
